name: Biome

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  biome:
    name: Run Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: "2.2.4"

    - name: Run Biome
      run: biome ci
